#!/usr/bin/python
#coding=utf-8

# This file is licensed under MIT license.
# See the LICENSE file in the project root for more information.

from car_core.behaviour_planner.behaviour_planner import main

if __name__ == "__main__":
    main()